### ISSUE TITLE
Send request to bank using HTTPS

### ISSUE THREAD

**Issue by theBull** [euforic/banking.js#19]
@euforic , I noticed in banking.js the request sent to the secure bank server is just using a standard HTTP request via superagent. I haven't used superagent much, but a brief search through their module didn't turn anything up for HTTPS, but maybe I'm blind. FYI, I might clone this repo and do a pull request for a version of banking.js that uses an HTTPS request instead. Very soon.

Cheers

**Comment by theBull** [comment]
correct me if I'm wrong - is the original request making an https request?

**Comment by euforic** [comment]
@theBull The urls are all defined by the banks so unless they have an https endpoint you have to use http. see http://www.ofxhome.com/index.php/home/directory

**Comment by theBull** [comment]
Cool, thanks. It was my bad for not fully understanding HTTPS and how it worked. All is good :sunglasses:
