### ISSUE TITLE
American Express does not seem to work

### ISSUE THREAD

**Issue by harrisonhjones** [euforic/banking.js#20]
Using http://www.ofxhome.com/index.php/institution/view/424 & http://wiki.gnucash.org/wiki/OFX_Direct_Connect_Bank_Settings as a guide I have the following bank options: 

    fid: 3101
  , fidOrg: 'AMEX'
  , url: 'https://online.americanexpress.com/myca/ofxdl/desktop/desktopDownload.do?request_type=nl_ofxdownload'
  , bankId: 'americanexpress.com' /* If bank account use your bank routing number otherwise set to null */
  , user: 'XXX'
  , password: 'XXX'
  , accId: 'XXX' /* Account Number */
  , accType: 'CREDITCARD' /* CHECKING || SAVINGS || MONEYMRKT || CREDITCARD */
  //, ofxVer: 103 /* default 102 */
  , app: 'QWIN' /* default  'QWIN' */
  , appVer: '1700' /* default 1700 */

I get a valid OFX response but it's just an error which contains the following error `The server does not support the CREDITCARDMSGSRQV1 request, or a request was made against an invalid organization.`

Any ideas?

**Comment by harrisonhjones** [comment]
I also get a `The server does not support the SIGNONMSGSRQV1 request, or a request was made against an invalid organization.`

**Comment by tricon** [comment]
I am having the same issue. I have been trying various settings with no success.

**Comment by tricon** [comment]
@harrisonhjones, Found the issue: https://github.com/euforic/banking.js/commit/1e389fccbee616ee85250a5d9de956674e9d2bb7

`npm install banking` is installing an older version that suffers this issue. Be sure to use a newer version.

**Comment by euforic** [comment]
I published the latest version to npm so it should be good to go now.
