### ISSUE TITLE
Credit card requests are not getting the DTEND field added

### ISSUE THREAD

**Issue by ansonlouis** [euforic/banking.js#39]
Pardon my very amateur knowledge in the OFX world, but it looks like not adding the DTEND field during credit card requests (the final else block in `createRequest`) is causing my bank to always return _all_ of my transactions. Adding in the DTEND field results in the proper amount of transactions (at least with my bank).

Is there any reason why this field isn't appended to the OFX request for credit card requests?

**Comment by euforic** [comment]
fix in v 1.0.1
