### ISSUE TITLE
headerString[key].split()

### ISSUE THREAD

**Issue by marcosmoski** [euforic/banking.js#40]
I had problemas with the function "parse()". 
The last object of array headerString on "lib/ofx.js" is a function, the split() doesn't work in that case. 

I corrected it with if(typeof != "function")

![image](https://cloud.githubusercontent.com/assets/20300698/16591602/0e2516d8-42b3-11e6-9e1d-d139edcda5a7.png)

This code is found in "banking/lib/ofx.js".

**Comment by euforic** [comment]
fixed with #41
