### ISSUE TITLE
Bank of America Says Software is outdated

### ISSUE THREAD

**Issue by adityavkk** [euforic/banking.js#44]
When trying to hit the BOA api it responds with a software is outdated error.

**Comment by euforic** [comment]
@adityavkk try changing the `appVers` to a higher number

```

var bank = Banking({
    fid: 10898
  , fidOrg: 'B1'
  , url: 'https://yourBanksOfxApiURL.com'
  , bankId: '0123456'
  , user: 'username'
  , password: 'password'
  , accId: '0123456789' 
  , accType: 'CHECKING'
  , ofxVer: 103
  , app: 'QBKS'
  , appVer: '2000' /*Change to higher than the default 1700*/
});
```

**Comment by euforic** [comment]
Closing issue, but feel free to reopen if your still having issues

**Comment by WillDent** [comment]
@euforic this is happening for me as well.  I have increased the appVer to 3000 and to no avail.
