### ISSUE TITLE
breaking change in XML parsing in minor version

### ISSUE THREAD

**Issue by dckc** [euforic/banking.js#46]
c072c4b4830fc149bf8706c0a293956ffbb986f6 was a breaking change without a new major version number.

Was that on purpose?

**Comment by euforic** [comment]
Well due to changing weather patterns and the global currency rates it made sense. lol

Mainly because I have OCD and thought  I should update the deps. I will do my best to uphold the semvar contract moving forward. Thanks for the catch.
