### ISSUE TITLE
Support for Promises

### ISSUE THREAD

**Issue by mrmarcsmith** [euforic/banking.js#51]
Hello, 
I would like to use promises like this:
```
return bank.getStatement({start:20170101, end:20180201}).then(function(response){
    //Do Something
},function(error){
    //Handle Error
});
```
but when I do that it only returns the XML with no parsed body. If I'm doing something wrong please correct me, otherwise what would it look like to add this feature?

**Comment by euforic** [comment]
You can just wrap it if you would like to use promises
```js
new Promise((resolve, reject) => {
  bank.getStatement({start:20170101, end:20180201}, (err, res) => {
    if (err) {
      reject(err)
      return    
    }
    resolve(res)
  })
})
```

**Comment by styfle** [comment]
You can use [util.promisify()](https://medium.com/front-end-hacking/promises-in-node-js-8-x-core-d6a8a93e85a2) in node.js if you are using 8.x or later.
