### ISSUE TITLE
CSV Output for transactions

### ISSUE THREAD

**Issue by mrbrahman** [euforic/banking.js#55]
I was wondering if you could add a feature to produce CSV output of the core transactions? This will help importing to xls or loading to a database.

Thanks!

**Comment by euforic** [comment]
You can just run that on the JSON response.

**Comment by mrbrahman** [comment]
Thanks! I'm new to nodejs and JavaScript, so still trying to figure that out.

`console.log(res)` only printed `[Object]` for the body. Reading through the documentation now to understand how this works. Slowly getting a handle on this :-)

**Comment by mrbrahman** [comment]
Separately (not related to this at all, but not sure who else/where else to ask), are the Check Free URLs (https://www.oasis.cfree.com/) trustworthy? Seems like a lot of financial institutions use them as the gateway?

**Comment by euforic** [comment]
Not sure about that.
