### ISSUE TITLE
Support for ASB bank in NZ. 

### ISSUE THREAD

**Issue by vaughanhale** [euforic/banking.js#56]
Support for ASB bank in NZ. (https://www.asb.co.nz/)

The readme says "Supports all financial institutions (File an issue if yours does not work)". I can't see support for ASB bank in NZ here (http://www.ofxhome.com/index.php/home/directory). Can this be added?

Thanks,
Vaughan

**Comment by euforic** [comment]
By that I mean, if your bank isn't working with the package. I am not the maintainer of ofxhome.com. So I would just check with your bank to find out the connection information.
