### ISSUE TITLE
npm install banking fail

### ISSUE THREAD

**Issue by khansen47** [euforic/banking.js#6]
Hey I feel like a failure, but I need some help, after install node and npm and all that. I type in the command npm install banking and get. 

npm ERR! Error: No compatible version found: banking
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:424:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:406:17
npm ERR!     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:136:7)
npm ERR!     at Object.cb [as oncomplete](/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 2.6.38-13-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "banking"
npm ERR! cwd /home/khansen/node
npm ERR! node -v v0.5.11-pre
npm ERR! npm -v 1.0.106

Please help me out!

**Comment by duard** [comment]
➜ npm install banking
npm WARN tar ENOENT: no such file or directory, open '/home/duard/development/api.solucoessig.xyz/APISig/node_modules/.staging/pathval-0e16d612/pathval.js'
npm WARN tar ENOENT: no such file or directory, open '/home/duard/development/api.solucoessig.xyz/APISig/node_modules/.staging/pathval-0e16d612/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/home/duard/development/api.solucoessig.xyz/APISig/node_modules/.staging/babel-polyfill-61492943/dist/polyfill.min.js'
npm WARN The package list-to-tree is included as both a dev and production dependency.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404 
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'APISig'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/duard/.npm/_logs/2019-06-28T10_52_41_023Z-debug.log
