### ISSUE TITLE
Best Practice for daily download

### ISSUE THREAD

**Issue by mrbrahman** [euforic/banking.js#60]
Not an issue really.

In case anyone stores the data that was downloaded, just wanted to find out what are the best practices (if there are any) for downloading transaction data daily considering:

1. Transactions that are posted late
2. Pending transactions (like the ones on credit card)

Thanks!

**Comment by euforic** [comment]
after 6pm and before 10am would be the best time to run an update since that is primarily the dead zone where no changes are made for banks

**Comment by mrbrahman** [comment]
Thanks for your reply!

But how would you handle the 2 scenarios I mentioned above? For e.g. I've seen that "pending transactions" on a credit card don't show up on the OFX download, but once they are confirmed, they seem to be posted with a previous date. In this case if I download everyday, I would miss those transactions.

A potential solution to the above scenario is to delay the download - say to T+3 (i.e. download today's transaction data only 3 days later). I'm wondering if the users of `banking.js` have faced similar issues and if so, what solutions did they adapt.

**Comment by euforic** [comment]
@mrbrahman so I was looking around and it is possible to get the pending we just need to add the api for it checkout https://github.com/aclindsa/ofxgo it is a really nice full featured ofx lib
