### ISSUE TITLE
Banco do Brasil not supported yet

### ISSUE THREAD

**Issue by arthurnobrega** [euforic/banking.js#65]
Hi guys!

First, congratulations for your great work on this project!

Do you plan to work with brazilian banks, like Banco do Brasil? In any answer, how can I be helpful?

Link of the bank: http://bb.com.br

**Comment by euforic** [comment]
All banks that support OFX access are supported I would check with you bank to make sure you are able to connect via OFX

**Comment by arthurnobrega** [comment]
> All banks that support OFX access are supported I would check with you bank to make sure you are able to connect via OFX

Hi euforic, 

Actually this bank I gave as example does not have a public url from where I can get an OFX file. It does export data as OFX, but only logging in manually.

You expect that the bank has a public url (API), right?

**Comment by euforic** [comment]
Yeah if there is a public API this lib will work if not you can always just use the OFX parser directly.
