### ISSUE TITLE
No response / no transactions with USAA

### ISSUE THREAD

**Issue by DanielSchaffer** [euforic/banking.js#8]
I'm trying to use this module to download transaction data from USAA. I can't really tell if I'm even getting a response - it looks like the "res" parameter is just echoing the request, as there is no BANKMSGSRSV1 element (or any other ofx "response" elements, even the signon), only BANKMSGSRQV1. I'm not sure how much more info I can give you without posting my bank info, so let me know what else would be helpful.

**Comment by davidlaprade** [comment]
I'm having issues with USAA as well that appear to be related to header delimiters. The error I'm getting:

```
OFXAdapter: Failed to parse request:
  Unable to parse an atomic field "OFXRequest.Headers.OFXHeader": unable to find end delimiters
```

I'm just using the stock commands suggested by the README:

```
  var bank = Banking({
    fid: 24591
  , fidOrg: 'USAA'
  , url: 'https://service2.usaa.com/ofx/OFXServlet'
  , bankId: 314074269
  , user: 'xxx'
  , password: 'xxx'
  , accId: xxxx
  , accType: 'SAVINGS'
});

bank.getStatement({start:20150101, end:20151001}, function(err, res){
  if(err) console.log(err)
  console.log(res);
});
```

@euforic @legastero if the problem is that USAA is expecting different header delimiters, how can I use different delimiters? Any help would be appreciated!

**Comment by euforic** [comment]
@davidlaprade try and modify https://github.com/euforic/banking.js/blob/master/lib/ofx.js#L32-L42 and see if that works. If it does I will test with my banks as well to ensure it does not break other banks and we can then PR it.

**Comment by karissa** [comment]
@euforic maybe a good way to do this would be to have a 'delimiter' parameter that defaults to '\n' so that it won't break other banks

**Comment by karissa** [comment]
OK, I opened a pull request with an optional `delimiter` parameter, does that work for you all? @DanielSchaffer @legastero @davidlaprade ?

**Comment by davidlaprade** [comment]
:+1:

**Comment by euforic** [comment]
@DanielSchaffer I would rather just change the `\n` to `\r\n` instead of passing another param especially if it wont break current banks.

**Comment by euforic** [comment]
@DanielSchaffer @karissa @legastero I pushed the requested delimiter change to version `0.4.0` and also updated all the dependencies. :-) hope that helps

**Comment by DanielSchaffer** [comment]
Hey guys, I never ended up using this lib. I've got no opinions on this :)

**Comment by withinboredom** [comment]
Hello, just peaking around the interwebs .. \r\n is the header protocol standard: http://stackoverflow.com/questions/5757290/http-header-line-break-style and https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2

Any sites that accept \n header line endings are doing so from the bottom of their heart and should have broken your lib a long time ago ;)
