### ISSUE TITLE
Chase Banking

### ISSUE THREAD

**Issue by sahlhoff** [euforic/banking.js#9]
Can anyone confirm Chase Banking?

I am getting an error reply response:

https://gist.github.com/4449695

and this is my bank info: 

https://gist.github.com/4449704

**Comment by alchemaLabs** [comment]
FYI Chase total checking doesn't work with JPMorgan Chase bank. It works with Chase (credit card) and NYC routing number:

    fid: 10898,
    fidOrg: 'B1',
    accType: 'CHECKING',
    accId: ‘123456789',
    bankId: '021000021',
    user: ‘username',
    password: ’s3cret',
    url: 'https://ofx.chase.com'

**Comment by thekingofspain** [comment]
I was able to download from chase with alchemaLabs info with one tweak.

The bankId is your checking accounts routing number, and mine was not 021000021, but rather 071000013.

Here is my config entry:

```
<site>
     SiteName : CHASE 
     AcctType : BASTMT
        fiorg : B1
          url : https://ofx.chase.com
          fid : 10898
       bankid : 071000013
     brokerid : 
        appid : 
       appver : 
  mininterval : 
</site> 
```

**Comment by theBull** [comment]
FYI, I think Chase only supports statement download, even though the OFX spec has a LOT more functionality available. Just in case anyone gets caught up in hours of pointless labor trying to do anything otherwise.

**Comment by thomasweng15** [comment]
@Grummle Your project has a deprecation notice in the Readme saying that Banking.js now works with Chase. Is this only the case if you pay the $10/mo. direct connection fee, or does Banking.js work without paying? If I still need to pay the fee, I'd rather scrape the mobile page.

**Comment by Grummle** [comment]
I believe you have to pay in order for banking.js to work. If seriously
suggest taking a look at https://plaid.com/

I was able to get ahold of chase banking info really quickly even when my
app is sandboxed.

**Comment by mladenmarkov** [comment]
@Grummle but you still have to enable Chase Direct Access (and pay $10/mo) when you use plaid.com, right?

**Comment by Grummle** [comment]
That I'm unsure of, but I don't think so. Give it a try and let us know!

**Comment by mladenmarkov** [comment]
I did try it out and it doesn't need Chase Direct Access to be enabled. My Plaid account is still in Pending state but I am able to access my Chase accounts.

**Comment by Grummle** [comment]
Plain has been very reliable for me, I pull my balance info and text it
every morning.I'm sure I'm probably not using it as intended but I'm also
playing with it for some side stuff.
